### ISSUE TITLE
Figure out github workflow to push to docker

### ISSUE THREAD

**Issue by bozdoz** [bozdoz/docker-wordpress-initialize#2]
```sh
docker build -t cli .
docker tag cli bozdoz/wordpress-initialize:latest
docker tag cli bozdoz/wordpress-initialize:1.2.3
docker push bozdoz/wordpress-initialize:latest
docker push bozdoz/wordpress-initialize:1.2.3
```

Need to add an access token here to github secrets, at minimum: https://hub.docker.com/settings/security

**Comment by bozdoz** [comment]
```yaml
 -     name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}
```
